name: tidy-bibliography

on:
  push:
    paths:
      - ".github/workflows/tidy-bib.yml"
      - "TreeSearch/**.bib"

  tidy-bib:
    name: Tidy bibliographies

    runs-on: ubuntu-22.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Download bibtool
        run: |
          wget http://mirrors.ctan.org/biblio/bibtex/utils/bibtool/BibTool-2.68.tar.gz
          gunzip < BibTool-2.68.tar.gz | tar -xf -
          cd BibTool
          cp makefile.unx makefile
          ./configure
          sudo make
          sudo make install
          sudo make install-sh
          sudo make clean

      - name: Sort bibliography
        run: |
          shopt -s nullglob # Don't enter loop if no matches
          for bib in TreeSearch/*.bib
          do
            echo "  > Sorting: $bib"
            bibtool -s -i "$bib" -o "$bib" --preserve.key.case=on
          done

      - name: Delete bibtool
        run: |
          rm -r BibTool # Uninstall, or its .bib files will be committed

      - name: Deploy revised bibliography
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git config --global pull.ff only
          git fetch
          git pull --ff-only
          git add *.bib
          git diff-index --quiet HEAD || git commit -m "Sort bib entries"
          git push
